### ISSUE TITLE
Exception while trying to run the python script

### ISSUE THREAD

**Issue by SrilakshmiMukalla** [AdobeDocs/pdfservices-api-documentation#357]
Issue in /src/pages/overview/pdf-accessibility-auto-tag-api/quickstarts.md

INFO:adobe.pdfservices.operation.pdfops.autotag_pdf_operation:All validations successfully done. Beginning AutotagPDF operation execution
Traceback (most recent call last):
  File "C:\Users\...i\Downloads\PDFServicesSDK-Python (Extract, Auto-tag)Samples\adobe-dc-pdf-services-sdk-python-samples\src\autotagpdf\autotag_pdf.py", line 45, in <module>
    autotag_output_files: AutotagPDFOutputFiles = autotag_pdf_operation.execute(execution_context)
  File "C:\Python39\lib\site-packages\adobe\pdfservices\operation\pdfops\autotag_pdf_operation.py", line 177, in execute
    raise ex
  File "C:\Python39\lib\site-packages\adobe\pdfservices\operation\pdfops\autotag_pdf_operation.py", line 153, in execute
    download_uri_list = AutotagPDFService.autotag_pdf(execution_context, self._source_file_ref, self.get_options(),
  File "C:\Python39\lib\site-packages\adobe\pdfservices\operation\internal\service\autotag_pdf_service.py", line 51, in autotag_pdf
    raise e
  File "C:\Python39\lib\site-packages\adobe\pdfservices\operation\internal\service\autotag_pdf_service.py", line 35, in autotag_pdf
    location = PlatformApi.submit_job(context, autotag_pdf_request, ServiceConstants.AUTOTAG_OPERATION_ENDPOINT,
  File "C:\Python39\lib\site-packages\adobe\pdfservices\operation\internal\api\platform_api.py", line 51, in submit_job
    response = http_client.process_request(http_request=http_request,
  File "C:\Python39\lib\site-packages\adobe\pdfservices\operation\internal\http\http_client.py", line 46, in process_request
    raise OperationException(message=response.text,
adobe.pdfservices.operation.internal.exceptions.OperationException

**Comment by cfjedimaster** [comment]
I assume you mean the sample, not the actual doc page which doesn't have the code. Autotag is in early release which means you need to be whitelisted to use the service, have you reached out to get your credentials whitelisted for testing?
