### ISSUE TITLE
PDF Embed API can't open password protected documents anymore

### ISSUE THREAD

**Issue by vivekkhatri** [AdobeDocs/pdfservices-api-documentation#600]
Issue in /src/pages/overview/pdf-embed-api/index.md

The Embed API seems longer be able to open a password protected document **IF** the document was protected by Microsoft Word. However, it can open a password-protected document if the password was added using the [Adobe Password Protect Tool](https://www.adobe.com/acrobat/online/password-protect-pdf.html).

The Chrome, Firefox and even Edge can open the same document, regardless of what we use to protect the document.

It does prompt to enter the password but upon entering the password, it logs the following error in the browser console:
`std::invalid_argument
    at ___cxa_throw (https://acrobatservices.adobe.com/dc-rendition-provider/3.0.2_5.4.0/AJS/wasm_acrobat.js:1:28684)
    at self.___cxa_throw (https://acrobatservices.adobe.com/dc-rendition-provider/3.0.2_5.4.0/AJS/wasm_acrobat.js:1:206)
    at https://acrobatservices.adobe.com/dc-rendition-provider/3.0.2_5.4.0/AJS/wasm_acrobat.wasm:wasm-function[3291]:0x278092
    at https://acrobatservices.adobe.com/dc-rendition-provider/3.0.2_5.4.0/AJS/wasm_acrobat.wasm:wasm-function[1250]:0xafebe
    at https://acrobatservices.adobe.com/dc-rendition-provider/3.0.2_5.4.0/AJS/wasm_acrobat.wasm:wasm-function[3426]:0x28164f
    at https://acrobatservices.adobe.com/dc-rendition-provider/3.0.2_5.4.0/AJS/wasm_acrobat.wasm:wasm-function[944]:0x76ceb
    at https://acrobatservices.adobe.com/dc-rendition-provider/3.0.2_5.4.0/AJS/wasm_acrobat.wasm:wasm-function[5103]:0x3d31b4
    at https://acrobatservices.adobe.com/dc-rendition-provider/3.0.2_5.4.0/AJS/wasm_acrobat.wasm:wasm-function[6076]:0x42004a
    at https://acrobatservices.adobe.com/dc-rendition-provider/3.0.2_5.4.0/AJS/wasm_acrobat.wasm:wasm-function[6066]:0x41f927
    at https://acrobatservices.adobe.com/dc-rendition-provider/3.0.2_5.4.0/AJS/wasm_acrobat.wasm:wasm-function[4570]:0x361a30
    at https://acrobatservices.adobe.com/dc-rendition-provider/3.0.2_5.4.0/AJS/wasm_acrobat.wasm:wasm-function[690]:0x5a085
    at https://acrobatservices.adobe.com/dc-rendition-provider/3.0.2_5.4.0/AJS/wasm_acrobat.wasm:wasm-function[6078]:0x42042e
    at https://acrobatservices.adobe.com/dc-rendition-provider/3.0.2_5.4.0/AJS/wasm_acrobat.wasm:wasm-function[6066]:0x41f990
    at https://acrobatservices.adobe.com/dc-rendition-provider/3.0.2_5.4.0/AJS/wasm_acrobat.wasm:wasm-function[4570]:0x361a30
    at https://acrobatservices.adobe.com/dc-rendition-provider/3.0.2_5.4.0/AJS/wasm_acrobat.wasm:wasm-function[690]:0x5a085
    at https://acrobatservices.adobe.com/dc-rendition-provider/3.0.2_5.4.0/AJS/wasm_acrobat.wasm:wasm-function[903]:0x72d6a
    at https://acrobatservices.adobe.com/dc-rendition-provider/3.0.2_5.4.0/AJS/wasm_acrobat.wasm:wasm-function[5023]:0x3c3219
    at https://acrobatservices.adobe.com/dc-rendition-provider/3.0.2_5.4.0/AJS/wasm_acrobat.wasm:wasm-function[992]:0x81165
    at https://acrobatservices.adobe.com/dc-rendition-provider/3.0.2_5.4.0/AJS/wasm_acrobat.wasm:wasm-function[402]:0x3286b
    at https://acrobatservices.adobe.com/dc-rendition-provider/3.0.2_5.4.0/AJS/wasm_acrobat.wasm:wasm-function[83]:0xd4f4
    at https://acrobatservices.adobe.com/dc-rendition-provider/3.0.2_5.4.0/AJS/wasm_acrobat.wasm:wasm-function[95]:0xddf6
    at https://acrobatservices.adobe.com/dc-rendition-provider/3.0.2_5.4.0/AJS/wasm_acrobat.wasm:wasm-function[10257]:0x5c2202
    at invoke_viii (https://acrobatservices.adobe.com/dc-rendition-provider/3.0.2_5.4.0/AJS/wasm_acrobat.js:1:103321)
    at https://acrobatservices.adobe.com/dc-rendition-provider/3.0.2_5.4.0/AJS/wasm_acrobat.wasm:wasm-function[4787]:0x386e29
    at https://acrobatservices.adobe.com/dc-rendition-provider/3.0.2_5.4.0/AJS/wasm_acrobat.wasm:wasm-function[9497]:0x503c48
    at ccall (https://acrobatservices.adobe.com/dc-rendition-provider/3.0.2_5.4.0/AJS/wasm_acrobat.js:1:79063)
    at https://acrobatservices.adobe.com/dc-rendition-provider/3.0.2_5.4.0/AJS/wasm_acrobat.js:1:79368
    at be (https://acrobatservices.adobe.com/dc-rendition-provider/3.0.2_5.4.0/AJS/acrobatProxy.js:2:79868)
    at Ae (https://acrobatservices.adobe.com/dc-rendition-provider/3.0.2_5.4.0/AJS/acrobatProxy.js:2:83764)
    at we (https://acrobatservices.adobe.com/dc-rendition-provider/3.0.2_5.4.0/AJS/acrobatProxy.js:2:85868)
    at Se (https://acrobatservices.adobe.com/dc-rendition-provider/3.0.2_5.4.0/AJS/acrobatProxy.js:2:85552)
    at https://acrobatservices.adobe.com/dc-rendition-provider/3.0.2_5.4.0/AJS/acrobatProxy.js:2:85830`

[Sample Doc locked by MS Word.pdf](https://github.com/AdobeDocs/pdfservices-api-documentation/files/11671128/Sample.Doc.locked.by.MS.Word.pdf)
[Sample Doc locked by Adobe online tool.pdf](https://github.com/AdobeDocs/pdfservices-api-documentation/files/11671133/Sample.Doc.locked.by.Adobe.online.tool.pdf)

**Comment by cfjedimaster** [comment]
Hi, this repo is for documentation issues only, not support. Please post your issue here: https://community.adobe.com/t5/acrobat-services-api/ct-p/ct-Document-Cloud-SDK?page=1&sort=latest_replies&filter=all&lang=all&tabid=discussions
